version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - subcomp-backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subcomp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data: {}
