name: Docker
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: "Build (${{ matrix.component }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.component }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ${{ matrix.component }}/Dockerfile
          tags: |
            ghcr.io/csesoc/subcomp-${{ matrix.component }}:${{ github.sha }}
            ghcr.io/csesoc/subcomp-${{ matrix.component }}:latest
          labels: ${{ steps.meta.outputs.labels }}
deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: [build]
    concurrency: production
    environment: production
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: csesoc/deployment
          token: ${{ secrets.GH_TOKEN }}
      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.27.2
      - name: Update deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "CSESoc CD"
          git config user.email "technical@csesoc.org.au"
          git checkout -b update/subcomp/${{ github.sha }}
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/subcomp-frontend:${{ github.sha }}"' apps/subcom/competitions/subcomp/deploy-frontend.yml
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/subcomp-backend:${{ github.sha }}"' apps/subcom/competitions/subcomp/deploy-backend.yml
          git add . 
          git commit -m "feat(subcomp): update images" 
          git push -u origin update/subcomp/${{ github.sha }}
          gh pr create --title "feat(subcomp): update image" --body "Updates the images for the subcomp deployment to commit csesoc/subcomp@${{ github.sha }}." > URL
          gh pr merge $(cat URL) --squash -d
