name: Docker
on:
  push:
    branches: [ "master" ]

jobs:
  build-backend:
    name: Build (Backend)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: backend
          builder: ${{ steps.buildx.outputs.name }}
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/csesoc/subcomp-backend:${{ github.sha }}
            ghcr.io/csesoc/subcomp-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-frontend:
    name: "Build (Frontend)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: frontend/Dockerfile
          tags: |
            ghcr.io/csesoc/subcomp-frontend:${{ github.sha }}
            ghcr.io/csesoc/subcomp-frontend:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    concurrency: production
    environment: production
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: csesoc/deployment
          token: ${{ secrets.GH_TOKEN }}
      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.27.2
      - name: Update deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "CSESoc CD"
          git config user.email "technical@csesoc.org.au"
          git checkout -b update/subcomp/${{ github.sha }}
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/subcomp-frontend:${{ github.sha }}"' apps/subcom/competitions/subcomp/deploy-frontend.yml
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/subcomp-backend:${{ github.sha }}"' apps/subcom/competitions/subcomp/deploy-backend.yml
          git add . 
          git commit -m "feat(subcomp): update images" 
          git push -u origin update/subcomp/${{ github.sha }}
          gh pr create --title "feat(subcomp): update image" --body "Updates the images for the subcomp deployment to commit csesoc/subcomp@${{ github.sha }}." > URL
          gh pr merge $(cat URL) --squash -d
